#!/bin/sh
# Authoritative desktop gate; see docs/VERIFICATION.md. Run from the repo root.
set -eu
sh tools/check-rust.sh
# Python native/packaging checks must use this source and toolchain, even when
# an older release binary is already present.
cargo build --release
python3 tools/assets/validate.py
# The package suite executes the texture CLI --check once.
python3 tools/props/build.py --check
python3 tools/assets/audit.py --workers 12 --out target/verification/asset-inventory.json
# The Halloween entity material contracts and exported clip seams are
# maintained assets; --check fails on a stale GLB.
python3 tools/entities/author_halloween_assets.py --check
python3 tools/entities/check_clip_boundaries.py
# The outdoor kit fixture is generated from the shipped scatter/asset tools and
# must match what those tools emit today.
python3 tools/levels/build_outdoor_fixture.py --check
# Places Demo's outdoor night slice is generated by its own idempotent tool.
python3 tools/levels/build_outdoor_route.py --check
python3 tools/levels/build_lantern_hollow.py --check
python3 tools/levels/build_lighting_quality.py --check
python3 tools/levels/build_winter.py --check
python3 -m unittest tests.test_showcase_assets tests.test_ghost_surface tests.test_lantern_hollow tests.test_weather tests.test_winter tests.test_winter_assets tests.test_string_lights
cargo test --lib showcase_audit
cargo test --lib static_prop_lighting_tests
cargo test --lib bundled_static_models_fit_medium_and_full_atlas_plans -- --ignored
# The bundled packages must be current for their sources and must decode.
cargo run --quiet --release --bin places-compile -- build assets/levels/places_demo.json --workers 12
cargo run --quiet --release --bin places-compile -- build assets/levels/model_zoo.json --workers 12
cargo run --quiet --release --bin places-compile -- build assets/levels/lantern_hollow.json --workers 12
cargo run --quiet --release --bin places-compile -- build assets/levels/movement_test.json --workers 12
cargo run --quiet --release --bin places-compile -- build assets/levels/winter.json --workers 12
# A package must be current for its source and assets: `verify --require-current`
# is the gate that fails when a rebuilt asset (a changed GLB or PNG) was not
# recompiled into the shipped package.
cargo run --quiet --release --bin places-compile -- verify assets/levels/places_demo.json --package assets/levels/places_demo.placesmap --require-current
cargo run --quiet --release --bin places-compile -- verify assets/levels/model_zoo.json --package assets/levels/model_zoo.placesmap --require-current
cargo run --quiet --release --bin places-compile -- verify assets/levels/lantern_hollow.json --package assets/levels/lantern_hollow.placesmap --require-current
cargo run --quiet --release --bin places-compile -- verify assets/levels/movement_test.json --package assets/levels/movement_test.placesmap --require-current
cargo run --quiet --release --bin places-compile -- verify assets/levels/winter.json --package assets/levels/winter.placesmap --require-current
cargo run --quiet --release --bin places-compile -- validate assets/levels/lantern_hollow.placesmap
cargo run --quiet --release --bin places-compile -- validate assets/levels/places_demo.placesmap
cargo run --quiet --release --bin places-compile -- validate assets/levels/model_zoo.placesmap
cargo run --quiet --release --bin places-compile -- validate assets/levels/movement_test.placesmap
cargo run --quiet --release --bin places-compile -- validate assets/levels/winter.placesmap
python3 -m unittest tests.test_package
python3 -m unittest tests.test_packaging tests.test_glb_accessors tests.test_asset_audit
python3 -m unittest tests.test_tool_execution tests.test_zoo_generator tests.test_bench_metrics tests.test_lightmap_harness tests.test_compiler_bench
python3 -m unittest tests.test_geometry_repair
cargo test --lib render::wgpu::renderer::low_lighting_tests -- --ignored --test-threads=1
python3 -m unittest tests.test_compiled_build
python3 -m unittest tests.test_wgpu_bootstrap
git diff --check
