#!/bin/sh
# Authoritative desktop gate; see docs/VERIFICATION.md. Run from the repo root.
set -eu
# Python native/packaging checks must use this source and toolchain, even when
# an older release binary is already present.
cargo build --release
python3 tools/assets/validate.py
# The package suite executes the texture CLI --check once.
python3 tools/props/build.py --check
python3 tools/assets/audit.py --workers 12 --out target/verification/asset-inventory.json
# The Halloween entity material contracts and exported clip seams are
# maintained assets; --check fails on a stale GLB.
python3 tools/entities/author_halloween_assets.py --check
python3 tools/entities/check_clip_boundaries.py
# The outdoor kit fixture is generated from the shipped scatter/asset tools and
# must match what those tools emit today.
python3 tools/levels/build_outdoor_fixture.py --check
# Places Demo's outdoor night slice is generated by its own idempotent tool.
python3 tools/levels/build_outdoor_route.py --check
python3 tools/levels/build_lantern_hollow.py --check
python3 tools/levels/build_lighting_quality.py --check
python3 tools/levels/build_winter.py --check
python3 tools/levels/build_capacity_fixtures.py --check
# Inventory source paths recursively, including local maps and nested controls.
# Build first: discovery tests must consume current packages and dependencies.
map_gate_root="target/verification/map-regression-$(date -u +%Y%m%dT%H%M%SZ)-$$"
python3 tools/bench/regression_maps.py --run-packages \
  --compiler target/release/places-compile --out "$map_gate_root" \
  --prepared-root target/verification/maps --install-source-packages
shasum -a 256 target/release/places-compile > "$map_gate_root/compiler-before.sha256"
# The player embeds the final Demo. Its rebuild must not change the compiler
# identity used by the packages just produced.
cargo build --release
shasum -a 256 target/release/places-compile > "$map_gate_root/compiler-after.sha256"
cmp "$map_gate_root/compiler-before.sha256" "$map_gate_root/compiler-after.sha256"
sh tools/check-rust.sh
cargo test --lib bundled_static_models_fit_medium_and_full_atlas_plans -- --ignored
python3 -m unittest discover -s tests -p 'test_*.py'
cargo test --lib render::wgpu::renderer::low_lighting_tests -- --ignored --test-threads=1
git diff --check
