#!/usr/bin/env python3
"""Author the Winter Place with the committed snow kit and ordinary geometry.

No textures, models, weather or movement behavior are generated by this tool.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import random
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'props'))
from string_lights import SPANS, attachment_height, lights

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / 'assets/levels/winter.json'
REVIEW_OUTPUT = ROOT / 'debug-maps/blizzard-20261007/sources/blizzard_review.json'
# x, z, floor_y, facade family. Entrances face south (+Z).
HOMES = ((-16, -16, .6, '02'), (8, -30, 0, '01'), (-17, 4, 0, '04'))
POND_ROOM = (4, -18, 16, 16)


def serialise(level: dict) -> str:
    return json.dumps(level, indent=2, ensure_ascii=False) + '\n'


def build_level() -> dict:
    catalog = {a['id']: a for a in json.loads((ROOT / 'assets/catalog.json').read_text())['assets']}
    level = {
        'format_version': 3, 'id': 'winter', 'name': 'Winter', 'author': 'Places',
        'spawn': {'x': 0, 'z': 12, 'yaw_degrees': -30},
        'defaults': {'wall': 'winter:stone_masonry_01', 'floor': 'winter:snow_01',
                     'ceiling': 'home:ceiling_white_01'},
        # Artwork is a background only; the existing cool fill and moon stay independent.
        'sky': {'texture': 'winter:tex_sky_aurora_01', 'brightness': .85, 'ambient': .24},
        'weather': {'kind': 'snow'},
        'global_illuminators': [{'id': 'winter_moon', 'kind': 'directional',
            'direction': [-.36, -.8, -.48], 'color': [.58, .72, 1], 'intensity': .18,
            'cast_shadows': True, 'bake': True, 'angular_size_degrees': .5}],
    }
    for key in ('rooms', 'walls', 'floor_patches', 'floor_regions', 'props', 'ceiling_lights',
                'doors', 'geometry_intent', 'void_walls', 'guardrails', 'stairs', 'ramps'):
        level[key] = []

    def prop(model, x, z, identity, *, y=0, yaw=0, scale=1, solid=False, size=None, **extra):
        p = {'id': identity.replace('.', '_'), 'model': model, 'x': round(x, 4), 'z': round(z, 4)}
        if y: p['y'] = round(y, 4)
        if yaw: p['rotation_degrees'] = round(yaw, 4)
        if scale != 1: p['scale'] = round(scale, 4)
        if solid:
            p.update(solid=True, size=size or catalog[model]['size'])
        p.update(extra)
        level['props'].append(p)

    def lamp(model, x, z, identity, y=0, yaw=0):
        offset, intensity, radius = {
            'outdoor:lamp_wall': ([0, .18, .12], .6, 5),
            'outdoor:lamp_stand': ([0, .86, 0], .7, 7),
            'outdoor:streetlight': ([0, 6.05, .43], 1.5, 14),
        }[model]
        lights = [{'shape': 'point', 'offset': offset, 'intensity': intensity,
                   'range': radius, 'color': [1, .81, .55], 'falloff': 'smooth'}]
        prop(model, x, z, identity, y=y, yaw=yaw, lights=lights,
             solid=model == 'outdoor:streetlight',
             size=[.16, 6.4, .16] if model == 'outdoor:streetlight' else None,
             occludes=False)

    def region(x, z, w, d, h, material='winter:snow_01'):
        level['floor_regions'].append({'x': x, 'z': z, 'width': w, 'depth': d,
            'offset_y': h, 'material': material, 'edge_material': material})

    def patch(x, z, w, d):
        level['floor_patches'].append({'x': x, 'z': z, 'width': w, 'depth': d,
            'material': 'winter:snow_packed_01'})

    def box(identity, minimum, maximum, material, *, solid=True):
        level['void_walls'].append({'id': identity, 'min': minimum, 'max': maximum,
            'material': material, 'faces': 'outward', 'solid': solid, 'occludes': solid})

    # Closed, single-storey cottages own their wall-edge floor and ceiling.
    for i, (x, z, floor, family) in enumerate(HOMES):
        cx, front = x + 4.5, z + 6
        level['rooms'].append({'x': x, 'z': z, 'width': 9, 'depth': 6, 'height': 2.7,
            'floor_y': floor, 'material': 'home:hardwood_oak_01',
            'ceiling': {'kind': 'gable', 'ridge': 'x', 'ridge_rise': 1.6},
            'ceiling_material': 'home:ceiling_white_01',
            'comment': ('Raised lodge' if i == 0 else f'Cottage {i}') + ': shared shingle roof with separate modeled snow caps.'})
        openings = [{'kind': 'door', 'offset': 3.93, 'width': 1.14, 'height': 2.15}]
        openings += [{'kind': 'window', 'offset': dx, 'width': 1.1, 'height': 1,
                      'sill': 1, 'glass': 'winter:window_amber_01', 'solid': True}
                     for dx in (1.1, 6.8)]
        level['walls'] += [
            {'x': x, 'z': front - .3, 'width': 9, 'depth': .3, 'y': floor,
             'material': 'winter:stone_masonry_01', 'faces': {'north': 'home:wall_paint_offwhite_01'},
             'openings': openings},
            {'x': x, 'z': z, 'width': 9, 'depth': .3, 'y': floor,
             'material': 'winter:stone_masonry_01', 'faces': {'south': 'home:wall_paint_offwhite_01'}},
            {'x': x, 'z': z + .28, 'width': .3, 'depth': 5.44, 'y': floor,
             'material': 'winter:stone_masonry_01', 'faces': {'east': 'home:wall_paint_offwhite_01'}},
            {'x': x + 8.7, 'z': z + .28, 'width': .3, 'depth': 5.44, 'y': floor,
             'material': 'winter:stone_masonry_01', 'faces': {'west': 'home:wall_paint_offwhite_01'}},
        ]
        if floor:
            # The raised room's floor is not a vertical foundation. Close the
            # exposed sky slot below its wall bases with real concrete skirts.
            # Tops tuck into wall solids; lapped corner planes stay distinct.
            for j, edge in enumerate((z, front-.2)):
                box(f'home_{i}_foundation_{j}',
                    [x-.06, -.12, edge-.04 if j == 0 else edge],
                    [x+9.06, floor+.04, edge+.2 if j == 0 else front+.04],
                    'winter:stone_masonry_01', solid=False)
            for j, edge in enumerate((x, x+8.84)):
                box(f'home_{i}_foundation_side_{j}',
                    [edge-.04 if j == 0 else edge, -.14, z+.16],
                    [edge+.16 if j == 0 else x+9.04, floor+.035, front-.16],
                    'winter:stone_masonry_01', solid=False)
        prop('winter:entrance_frame', cx, front + .08, f'home_{i}_doorway')
        level['doors'].append({'id': f'home_{i}_door', 'x': cx - .55, 'z': front - .15,
            'width': 1.1, 'height': 2.15, 'thickness': .045, 'open_direction': 'left',
            'swing_degrees': 90, 'open_speed_degrees': 100, 'initial_state': 'open',
            'kind': 'interior', 'frame_depth': .7, 'frame_center': .2,
            'material': 'winter:timber_01', 'frame_material': 'winter:timber_01',
            'components': [{'component': 'interactable', 'prompt': 'Lodge door' if i == 0 else 'Cottage door'}],
            'bindings': [{'on': 'interact', 'actions': [{'action': 'toggle'}]}]})
        # Two 1.4x kit bays span 9.52 m. Measured slopes meet at the ridge,
        # extend 0.64 m beyond the front/back walls, and clear the sealed ceiling.
        for bay, dx in enumerate((-2.38, 2.38)):
            for side, dz, yaw in (('front', 1.82, 0), ('back', -1.82, 180)):
                prop(f'outdoor:house_{family}_roof_slope', cx + dx, z + 3 + dz,
                     f'home_{i}_roof_{bay}_{side}', y=2.7, yaw=yaw, scale=1.4)
            prop(f'outdoor:house_{family}_roof_ridge', cx + dx, z + 3,
                 f'home_{i}_ridge_{bay}', y=4.996, scale=1.4)
        for side, dx, yaw in (('west', -4.65, 270), ('east', 4.65, 90)):
            base = .045217 if family == '01' else .060122
            prop(f'outdoor:house_{family}_gable', cx + dx, z + 3,
                 f'home_{i}_gable_{side}', y=floor + 2.7 - base * 2.4, yaw=yaw, scale=2.4)
        # Preserve the foundation eave colliders as timber fascia. Snow now
        # rests on the actual roof above, rather than whitening these boxes.
        for j, edge in enumerate((z, front)):
            box(f'home_{i}_eave_{j}', [x - .4, floor + 2.7, edge - .45],
                [x + 9.4, floor + 2.82, edge + .45], 'winter:timber_01')
        for dx in (-1.1, 1.1):
            lamp('outdoor:lamp_wall', cx + dx, front + .4, f'home_{i}_lamp_{dx}', y=floor + 1.79)
        level['ceiling_lights'].append({'id': f'home_{i}_light', 'fixture': 'home:ceiling_light_round',
            'x': cx + 1.3, 'z': z + 3.3, 'brightness': 1.1, 'range': 7,
            'color': [1, .83, .60], 'emission': 1, 'align': 'none'})
        prop('core:couch', x + 2, z + 1.4, f'home_{i}_couch', solid=True)
        prop('core:table', x + 2, z + 3.1, f'home_{i}_table', solid=True)
        prop('core:bed', x + 7, z + 2, f'home_{i}_bed', solid=True)
        prop('core:bookshelf', x + 7, z + 4.8, f'home_{i}_shelf', solid=True)
        if i:
            patch(cx - .85, front, 1.7, 4)

    # Partition ground at cottage bounds, with intermediate tile edges to
    # keep outdoor light grids compact. No snow floor hides under an interior.
    # Keep the lowered pond inside one room: a negative region crossing room
    # borders emits room-edge skirts, even when both rooms share floor_y.
    px, pz, pw, pd = POND_ROOM
    level['rooms'].append({'x': px, 'z': pz, 'width': pw, 'depth': pd,
        'height': 10, 'ceiling': {'kind': 'open'}, 'material': 'winter:snow_01',
        'comment': 'Pond shore: one room owns the entire recessed ice surface.'})
    level['geometry_intent'].append({'check': 'missing-wall', 'x': px, 'z': pz,
        'width': pw, 'depth': pd, 'note': 'Open pond and shoreline inside the visible rock boundary.'})
    zs = (-40, -30, -24, -18, -16, -10, -2, 0, 4, 10, 20)
    for za, zb in zip(zs, zs[1:]):
        active = [(x, z) for x, z, _, _ in HOMES if z < (za + zb) / 2 < z + 6]
        # Only split at a house's X bounds in the bands actually containing
        # that house. Global cuts would produce one-metre-wide probe-less rooms.
        pond_band = pz < (za + zb) / 2 < pz + pd
        xs = sorted({-24, 0, 24} | {edge for x, _ in active for edge in (x, x + 9)}
                    | ({px, px + pw} if pond_band else set()))
        xs = sorted(set(xs) | {(a + b) / 2 for a, b in zip(xs, xs[1:]) if b - a > 16})
        for xa, xb in zip(xs, xs[1:]):
            if (pond_band and px < (xa + xb) / 2 < px + pw) or any(x < (xa + xb) / 2 < x + 9 for x, _ in active):
                continue
            level['rooms'].append({'x': xa, 'z': za, 'width': xb - xa, 'depth': zb - za,
                'height': 10, 'ceiling': {'kind': 'open'}, 'material': 'winter:snow_01',
                'comment': 'Snow ground; one continuous walkable settlement.'})
            level['geometry_intent'].append({'check': 'missing-wall', 'x': xa, 'z': za,
                'width': xb - xa, 'depth': zb - za,
                'note': 'Deliberate outdoor snow floor, contained by visible collidable rock escarpments.'})
    for x, z, w, d in ((-26.2, -42.2, 2.2, 64.4), (24, -42.2, 2.2, 64.4),
                       (-24, -42.2, 48, 2.2), (-24, 20, 48, 2.2)):
        level['geometry_intent'].append({'check': 'room-leak', 'x': x, 'z': z, 'width': w, 'depth': d,
            'note': 'Outside authored floors, behind the visible solid rock boundary; native movement audits verify containment.'})

    # Packed walking lines meet a broad untrampled gathering area. Avoid a
    # six-metre rectangular material stamp across the whole square.
    patch(-1, -5, 2, 10)
    patch(-3.8, 1.6, 2.8, 1.5)
    patch(-1, -37, 2, 32)
    patch(-1, 5, 2, 12)
    patch(-11.5, -4.6, 11.5, 1.7)
    patch(0, -21.5, 12.5, 1.7)
    patch(11.65, -24, 1.7, 2.5)
    patch(-12.5, 12.3, 12.5, 1.7)
    patch(-13.35, 10, 1.7, 2.3)
    patch(3, -1.8, 15, 1.6)
    patch(17, -18, 1.6, 16.2)
    patch(0, -18, 18.6, 1.6)

    # Raised lodge deck: side stairs ascend +X; front ramp descends +Z.
    region(-15, -10, 7, 2.4, .6, 'home:hardwood_oak_01')
    level['stairs'].append({'x': -17.4, 'z': -9.6, 'width': 2.4, 'depth': 1.2,
        'offset_y': 0, 'rise': .6, 'steps': 3, 'material': 'winter:snow_packed_01',
        'riser_material': 'winter:stone_masonry_01', 'side_material': 'winter:stone_masonry_01'})
    level['ramps'].append({'x': -12.1, 'z': -7.6, 'width': 1.2, 'depth': 3,
        'offset_y': .6, 'rise': -.6, 'material': 'winter:snow_packed_01',
        'edge_material': 'winter:snow_01'})
    for x, length in ((-15, 2.85), (-10.85, 2.85)):
        level['guardrails'].append({'x': x, 'z': -7.65, 'y': .6, 'length': length,
            'height': 1.05, 'material': 'winter:timber_01'})
    # Sheltered terrace has a supported roof and a 2.7 m clear ceiling.
    box('lodge_awning', [-15.2, 3.33, -10.05], [-7.8, 3.51, -7.45], 'winter:timber_01')
    for x in (-14.8, -8.2):
        prop('outdoor:house_02_porch_post', x, -7.85, f'porch_post_{x}', scale=1.187,
             solid=True, size=[.14, 2.3, .14])

    # Solid frozen water replaces the liquid volume at the waterline. The
    # material owns traction; the ordinary floor and rim own all collision.
    # A shallow opaque backing gives the blended surface readable depth.
    region(6, -16, 10, 12, -.16, 'winter:ice_01')
    box('pond_ice_depth', [6, -.36, -16], [16, -.31, -4], 'winter:ice_depth_01', solid=False)
    # Shallow tapered shore shelves replace four identical raised corner
    # platforms. Three short strips describe each clipped corner; dry drifts
    # soften their outline, while the west crossing stays at the old waterline.
    for east, south in ((False, False), (True, False), (False, True), (True, True)):
        for strip, width in enumerate((2.4, 1.65, .9)):
            x = 16-width if east else 6
            z = -4-(strip+1)*.6 if south else -16+strip*.6
            region(x, z, width, .6, 0)
    # A pond railing leaves the west/south shore open for walking onto ice.
    level['guardrails'].append({'x': 16.8, 'z': -15, 'length': 10, 'rotation_degrees': 270,
        'height': 1.05, 'material': 'winter:timber_01'})
    for i, (x, z) in enumerate(((-3.5, 2.5), (4, -2), (2.8, -21), (-12.5, 14.4))):
        lamp('outdoor:lamp_stand', x, z, f'path_lamp_{i}')
    # A single modest beacon marks the forest resting place in severe weather.
    # Leave the surrounding grove cold rather than filling it with path lamps.
    lamp('outdoor:lamp_stand', -2.8, -32.6, 'forest_rest_lamp')
    level['props'][-1]['lights'][0].update(intensity=.42, range=4.5)
    for i, (x, z) in enumerate(((-3.8, -3), (13.8, -21.8))):
        prop('winter:timber_lantern', x, z, f'square_lamp_{i}', solid=True,
             size=[.155, 2.6, .155], occludes=False,
             lights=[{'shape': 'point', 'offset': [0, 2.60, .12], 'intensity': 1.5,
                      'range': 14, 'color': [1, .81, .55], 'falloff': 'smooth'}])
    for i, (x, z) in enumerate(((7, -18), (18.8, -10), (5, -5), (-6, -25), (-5, 6))):
        prop('winter:boulder_snow' if i != 3 else 'outdoor:showcase_boulder', x, z, f'boulder_{i}', yaw=i * 47,
             scale=1 + (i % 3) * .18, solid=True, size=[1.4, .85, 1.3])
    for i, (x, z) in enumerate(((-5.6, 1), (4.6, 3), (-3.5, -31))):
        prop('outdoor:showcase_stump_seat', x, z, f'seat_{i}', solid=True)

    # Visible high rock faces contain the map, without invisible blockers.
    for side, x, yaw in (('west', -24, 90), ('east', 24, 270)):
        for i in range(16):
            prop('winter:rock_face_snow' if i % 3 else 'outdoor:showcase_rock_face', x, -38 + i * 3.8, f'boundary_{side}_{i}',
                 yaw=yaw, solid=True, size=[4, 5, 2.2], occludes=False)
    for side, z, yaw in (('north', -40, 0), ('south', 20, 180)):
        for i in range(13):
            prop('winter:rock_face_snow' if i % 3 else 'outdoor:showcase_rock_face', -23 + i * 3.8, z, f'boundary_{side}_{i}',
                 yaw=yaw, solid=True, size=[4, 5, 2.2], occludes=False)

    # Reference masonry edges and lantern piers flank circulation. All solid
    # boxes stay outside the existing path, ramp and pond approach footprints.
    for side in (-1, 1):
        for j, z in enumerate((-14.4, -11.9, -26.5, -29.0)):
            prop('winter:stone_wall_snow', side*2.35, z, f'path_wall_{side}_{j}',
                 yaw=90, solid=True, size=[.5, .98, 2.4])
        for j, z in enumerate((-16.2, -10.2)):
            prop('winter:masonry_pier_snow', side*2.35, z, f'path_pier_{side}_{j}',
                 solid=True, size=[.65, 1.16, .65])
            if j == 1:
                prop('outdoor:lamp_fence', side*2.35, z, f'path_pier_lantern_{side}', y=1.151,
                     occludes=False, lights=[{'shape':'point', 'offset':[0,.18,0],
                     'intensity':.4, 'range':4, 'color':[1,.81,.55], 'falloff':'smooth'}])
    for j, (x,z) in enumerate(((-3.7,-5.5),(3.7,-5.5),(-3.7,5.7),(3.7,5.7))):
        prop('winter:masonry_pier_snow', x, z, f'square_pier_{j}',
             solid=True, size=[.65,1.16,.65])
    for j, (x,z,yaw,scale) in enumerate(((9.6,-15.3,14,.75),(14.8,-5.3,70,.65),(6.7,-13.5,34,.5))):
        prop('winter:ice_fragment', x, z, f'pond_fragment_{j}', y=-.006, yaw=yaw, scale=scale)
    # Reuse the reconstructed real distant geology behind containment.
    for j, (x,z,yaw,scale) in enumerate(((-17,-45,0,1.15),(6,-46,0,1.2),(25,-31,90,1),(-27,-28,90,1.05))):
        prop('outdoor:boundary_ridge', x, z, f'distant_ridge_{j}', yaw=yaw, scale=scale, occludes=False)

    # Snow variants retain every canonical base vertex, UV, colour and material.
    # Exposed perimeter trees carry more snow; sheltered trees have a lighter load.
    rng = random.Random(20261006)
    for row, z in enumerate(range(-36, 18, 4)):
        for col, x in enumerate(range(-20, 22, 4)):
            px, pz = x + rng.uniform(-1.35, 1.35), z + rng.uniform(-1.35, 1.35)
            # Gaps between small groves break the repeated grid and expose
            # isolated silhouettes. The central walking spine stays clear.
            if (row*7+col*3) % 11 in (0, 1): continue
            if abs(px) < 3 or (-6 < px < 6 and -7 < pz < 7): continue
            if any(hx - 2 < px < hx + 11 and hz - 2 < pz < hz + 10 for hx, hz, _, _ in HOMES): continue
            if -19 < px < -6 and -18 < pz < -3: continue
            if 3 < px < 20 and -20 < pz < 1: continue
            if -15 < px < 3 and 10 < pz < 16: continue
            if 0 < px < 15 and -24 < pz < -18: continue
            if math.hypot(px+3.5, pz+31) < 2 or math.hypot(px+2.8, pz+32.6) < 1.8: continue
            snow_model = 'winter:tree_snow_02' if abs(px) > 15 or (row + col) % 4 == 0 else 'winter:tree_snow_01'
            prop(snow_model, px, pz, f'forest_{row}_{col}',
                 yaw=rng.uniform(0, 360), scale=rng.uniform(.72, 1.14),
                 solid=True, size=[.6, 6.8, .6], occludes=False)
    # Keep the existing bank traversal; drifts soften its hard edge.
    region(-21, -25, 5, 5, .28)
    level['ramps'].append({'x': -21, 'z': -20, 'width': 5, 'depth': 5.5,
        'offset_y': .28, 'rise': -.28, 'material': 'winter:snow_01', 'edge_material': 'winter:snow_01'})

    def local_floor(x, z):
        # The maintained Winter source has axis-aligned stairs/ramps. Match
        # LevelSurfaces' rendered tread/region height, not the walking pitch.
        room = next((r for r in level['rooms'] if r['x']-.01 <= x <= r['x']+r['width']+.01
                     and r['z']-.01 <= z <= r['z']+r['depth']+.01), None)
        if room is None:
            raise ValueError(f'Snow anchor ({x}, {z}) is outside the authored floor')
        floor = room.get('floor_y', 0)
        height = floor
        for r in level['floor_regions']:
            if r['x'] <= x <= r['x']+r['width'] and r['z'] <= z <= r['z']+r['depth']:
                height = floor + r['offset_y']
        for key in ('ramps', 'stairs'):
            for r in level[key]:
                if r['x'] <= x <= r['x']+r['width'] and r['z'] <= z <= r['z']+r['depth']:
                    along = (x-r['x'])/r['width'] if key == 'stairs' else (z-r['z'])/r['depth']
                    if key == 'stairs':
                        along = min(r['steps'], math.floor(along*r['steps'])+1)/r['steps']
                    height = floor + r['offset_y'] + along*r['rise']
        return height

    def mounted(model, x, z, identity, height, **extra):
        prop('winter:'+model, x, z, identity, y=height-local_floor(x, z), **extra)

    def icicles(model, x, z, identity, underside, **extra):
        height = catalog['winter:'+model]['size'][1]*extra.get('scale', 1)
        mounted(model, x, z, identity, underside+.015-height, **extra)

    # Modular snow on roof slopes, windward eaves, doorway hoods and window
    # ledges. Leave ridges, several roof edges and sheltered timber exposed.
    for i, (x, z, floor, family) in enumerate(HOMES):
        cx, front = x+4.5, z+6
        for bay, dx in enumerate((-2.38, 2.38)):
            for side, dz, yaw in (('front', 1.96, 0), ('back', -1.96, 180)):
                mounted('snow_roof_slope', cx+dx, z+3+dz, f'home_{i}_snow_roof_{bay}_{side}',
                        floor+2.7+.20846*1.4-.008, yaw=yaw, scale=1.4)
        for j, dx in enumerate((-3.6, -1.2, 1.2, 3.6)):
            mounted('snow_roof_edge', cx+dx, front+.5, f'home_{i}_snow_eave_{j}',
                    floor+2.7+.16*1.4-.008)
            # The lodge's awning shelters this eave. Cottage corner loads stay
            # clear of door lamps and the entrance hood beneath the centre.
            if i and j in (0, 3):
                icicles('icicle_cluster_sparse' if j % 2 else 'icicle_cluster_mixed',
                        cx+dx, front+.60, f'home_{i}_eave_icicles_{j}', floor+2.7)
        for j, dx in enumerate((1.65, 7.35)):
            mounted('window_frame', x+dx, front+.09, f'home_{i}_window_{j}', floor+.95)
            # The lodge windows are beneath the sealed awning; they stay dry.
            if i:
                mounted('snow_ledge', x+dx, front+.14, f'home_{i}_snow_sill_{j}', floor+1.002)
                icicles('icicle_short', x+dx+(.22 if j == 0 else -.3), front+.24,
                        f'home_{i}_sill_icicle_{j}', floor+.94, scale=.8 if j else 1)
        if i:
            mounted('door_hood_snow', cx, front+.34, f'home_{i}_door_hood', floor+2.20)
            icicles('icicle_cluster_sparse', cx, front+.73, f'home_{i}_door_icicles', floor+2.50)
        # Building bases: asymmetric outside banks, away from openings/paths.
        for j, dx in enumerate((.9, 8.1) if i else ()):
            mounted('drift_wall', x+dx, front+(.31 if j == 0 else .20), f'home_{i}_wall_drift_{j}', -.008,
                    yaw=0 if j == 0 else 8, scale=(.52, .72, .6)[i] if j == 0 else (.68, .48, .78)[i])
        mounted('drift_medium', x-.68, z+1.5, f'home_{i}_side_drift', -.008, yaw=90)

    for j, x in enumerate((-14, -11.6, -9.2)):
        mounted('snow_awning', x, -8.75, f'lodge_awning_snow_{j}', 3.502)
    # Separated groups flank a clear entrance, with only a short centre drip.
    for j, (model, x, scale) in enumerate((('icicle_cluster_mixed', -14.1, .88),
                                          ('icicle_short', -11.85, .85),
                                          ('icicle_cluster_sparse', -8.95, .72))):
        icicles(model, x, -7.47, f'lodge_awning_icicles_{j}', 3.33, scale=scale)
    icicles('icicle_long', -14.8, -7.47, 'lodge_awning_icicle_long', 3.33)
    icicles('icicle_medium', -8.2, -7.47, 'lodge_awning_icicle_medium', 3.33)
    # Only the side of each stair tread holds snow; the walking line stays packed.
    for step in range(3):
        mounted('snow_stair_edge', -17.0+step*.8, -9.48, f'lodge_stair_snow_{step}',
                (step+1)*.2-.008, yaw=90)

    # Add snow to the original guardrails, preserving their exact dimensions,
    # collision, post spacing and height. Top loads vary along each run.
    for index, rail in enumerate(level['guardrails']):
        if index < 2:
            # Both porch rails lie fully beneath the awning. No snow on the
            # deck, rail tops, sheltered sills or sealed lower rail space.
            continue
        angle = math.radians(rail.get('rotation_degrees', 0))
        def rail_point(along):
            return rail['x']+math.cos(angle)*along, rail['z']-math.sin(angle)*along
        base = rail.get('y', local_floor(rail['x'], rail['z']))
        length = rail['length']
        for j in range(math.ceil(length/1.2)):
            span = min(1.2, length-j*1.2)
            px, pz = rail_point(j*1.2+span/2)
            mounted('snow_rail_top', px, pz, f'rail_{index}_snow_{j}', base+rail['height']-.008,
                    yaw=rail.get('rotation_degrees', 0), scale=span/1.2)
            if j % 3 == 0:
                mounted('snow_rail_top', px, pz, f'rail_{index}_lower_snow_{j}', base+.322,
                        yaw=rail.get('rotation_degrees', 0), scale=span/1.2*.72)
        posts = [j*1.2 for j in range(math.floor(length/1.2)+1)]
        if length-posts[-1] < .3:
            posts[-1] = length
        elif length-posts[-1] > .03:
            posts.append(length)
        for j, along in enumerate(posts):
            px, pz = rail_point(along)
            mounted('snow_post_cap', px, pz, f'rail_{index}_post_snow_{j}', base+rail['height']-.008)
        px, pz = rail_point(length*.63)
        # Keep the pond-side drift above dry shore, never floating over ice.
        mounted('drift_fence', px, pz,
                f'rail_{index}_drift', -.008,
                yaw=rail.get('rotation_degrees', 0))

    # Low, supported shoreline loads gather outside the ice footprint. Open
    # west/south entries retain their shallow step and visible snow/ice boundary.
    for j, (model, x, z, yaw, scale) in enumerate((
        ('drift_medium', 6.65, -15.7, 24, .7),
        ('drift_small', 6.3, -4.4, 110, .64),
        ('drift_medium', 14.8, -15.8, 158, .62),
        ('drift_small', 9.4, -3.75, 180, .6),
        ('drift_small', 13.3, -3.6, 168, .45),
        ('drift_medium', 15.6, -4.35, 235, .58),
    )):
        mounted(model, x, z, f'pond_shore_snow_{j}', -.008, yaw=yaw, scale=scale)

    # A range of drift scales near tree roots, boulders, the bank and shoreline.
    # The clear centre/forest spine, ramps and ice entry remain unburied.
    for j, (model, x, z, yaw) in enumerate((
        ('drift_small', -5.7, 5.5, 35), ('drift_medium', -6.4, -24, 110),
        ('drift_large', -20, -26.8, 10), ('drift_large', 21.3, -32, 75),
        ('mound_irregular', 19.4, -8.8, 23), ('mound_irregular', -19.5, 1, 130),
        ('drift_small', 5.2, -3.8, 45), ('drift_medium', 15.1, -17.4, 165),
        ('drift_wall', 21.7, 12, 90), ('drift_fence', 3.5, -30.5, 25),
    )):
        prop('winter:'+model, x, z, f'landscape_drift_{j}', y=-.008, yaw=yaw)

    # A few warm destinations, leaving the forest/pond and most facades cold.
    # Source offsets and cable anchors are shared with the GLB authoring tool.
    def string(variant, x, z, identity, anchor_y, intensity=.32, radius=4.5, yaw=0):
        mounted('string_lights_'+variant, x, z, identity,
                anchor_y-attachment_height(variant), occludes=False,
                yaw=yaw, lights=lights(variant, intensity, radius))

    # Small timber brackets project from the fascia past the snowy door hood.
    # The glass stays clear of the snow/hood and its hanging icicle roots.
    for i in (1, 2):
        x, z, floor, _ = HOMES[i]
        for side in (-1, 1):
            anchor = x+4.5+side*1.4
            box(f'home_{i}_string_bracket_{side}', [anchor-.055, floor+2.725, z+6+.43],
                [anchor+.055, floor+2.795, z+6+.89], 'winter:timber_01', solid=False)
        string('short', x+4.5, z+6+.86, f'home_{i}_string', floor+2.76)
    # Lodge spans hang between the existing awning posts and below the two
    # front rails. Keep the gap above the ramp open and the icicle line clear.
    string('long', -11.5, -7.78, 'lodge_porch_string', 3.25)
    for i, x in enumerate((-13.575, -8.475)):
        string('short', x, -7.55, f'lodge_rail_string_{i}', 1.54, .10, 3.0)

    # Ordinary narrow timber posts support the square and one path crossing.
    # Their bases sit outside the packed walking lines and seating footprints.
    for i, (variant, x, z, yaw) in enumerate((('long', .5, -3.6, 8), ('long', -.5, 3.8, -12),
                                              ('medium', 0, -8.0, 5))):
        span = SPANS[variant][0]
        angle = math.radians(yaw)
        for side in (-1, 1):
            prop('outdoor:house_02_porch_post', x+side*span/2*math.cos(angle),
                 z-side*span/2*math.sin(angle),
                 f'string_post_{i}_{side}', scale=1.35, solid=True, size=[.14, 2.3, .14])
        string(variant, x, z, f'square_string_{i}' if i < 2 else 'path_string', 3.02, yaw=yaw)
    return level


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    level = build_level()
    # Preserve the existing severe mode's exact identity and weather settings;
    # its current scene must follow Winter, while its frozen evidence stays put.
    review = json.loads(REVIEW_OUTPUT.read_text())
    severe = {**level, **{key: review[key] for key in ('id', 'name', 'weather')}}
    for path, source in ((OUTPUT, level), (REVIEW_OUTPUT, severe)):
        expected = serialise(source)
        if args.check:
            if not path.is_file() or path.read_text() != expected:
                print(f'{path.name} is stale; run tools/levels/build_winter.py')
                return 1
        else:
            path.write_text(expected)
            print(f'Authored {path}')
    if args.check:
        print('Winter and severe review sources are deterministic and current')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
