#!/usr/bin/env python3
"""Author the Winter Place foundation using shared PNG assets and ordinary geometry.

No textures, models, weather or movement behavior are generated by this tool.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import random

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / 'assets/levels/winter.json'
# x, z, floor_y, facade family. Entrances face south (+Z).
HOMES = ((-16, -16, .6, '02'), (8, -30, 0, '01'), (-17, 4, 0, '04'))
POND_ROOM = (4, -18, 16, 16)


def serialise(level: dict) -> str:
    return json.dumps(level, indent=2, ensure_ascii=False) + '\n'


def build_level() -> dict:
    catalog = {a['id']: a for a in json.loads((ROOT / 'assets/catalog.json').read_text())['assets']}
    level = {
        'format_version': 3, 'id': 'winter', 'name': 'Winter', 'author': 'Places',
        'spawn': {'x': 0, 'z': 12, 'yaw_degrees': -30},
        'defaults': {'wall': 'outdoor:house_siding_01', 'floor': 'winter:snow_01',
                     'ceiling': 'home:ceiling_white_01'},
        'sky': {'texture': 'outdoor:tex_sky_stars_01', 'brightness': .85, 'ambient': .24},
        'global_illuminators': [{'id': 'winter_moon', 'kind': 'directional',
            'direction': [-.36, -.8, -.48], 'color': [.58, .72, 1], 'intensity': .18,
            'cast_shadows': True, 'bake': True, 'angular_size_degrees': .5}],
    }
    for key in ('rooms', 'walls', 'floor_patches', 'floor_regions', 'props', 'ceiling_lights',
                'doors', 'geometry_intent', 'void_walls', 'guardrails', 'stairs', 'ramps'):
        level[key] = []

    def prop(model, x, z, identity, *, y=0, yaw=0, scale=1, solid=False, size=None, **extra):
        p = {'id': identity.replace('.', '_'), 'model': model, 'x': round(x, 4), 'z': round(z, 4)}
        if y: p['y'] = round(y, 4)
        if yaw: p['rotation_degrees'] = round(yaw, 4)
        if scale != 1: p['scale'] = round(scale, 4)
        if solid:
            p.update(solid=True, size=size or catalog[model]['size'])
        p.update(extra)
        level['props'].append(p)

    def lamp(model, x, z, identity, y=0, yaw=0):
        offset, intensity, radius = {
            'outdoor:lamp_wall': ([0, .18, .12], .6, 5),
            'outdoor:lamp_stand': ([0, .86, 0], .7, 7),
            'outdoor:streetlight': ([0, 6.05, .43], 1.5, 14),
        }[model]
        lights = [{'shape': 'point', 'offset': offset, 'intensity': intensity,
                   'range': radius, 'color': [1, .81, .55], 'falloff': 'smooth'}]
        prop(model, x, z, identity, y=y, yaw=yaw, lights=lights,
             solid=model == 'outdoor:streetlight',
             size=[.16, 6.4, .16] if model == 'outdoor:streetlight' else None)

    def region(x, z, w, d, h, material='winter:snow_01'):
        level['floor_regions'].append({'x': x, 'z': z, 'width': w, 'depth': d,
            'offset_y': h, 'material': material, 'edge_material': material})

    def patch(x, z, w, d):
        level['floor_patches'].append({'x': x, 'z': z, 'width': w, 'depth': d,
            'material': 'winter:snow_packed_01'})

    def box(identity, minimum, maximum, material, *, solid=True):
        level['void_walls'].append({'id': identity, 'min': minimum, 'max': maximum,
            'material': material, 'faces': 'outward', 'solid': solid, 'occludes': solid})

    # Closed, single-storey cottages own their wall-edge floor and ceiling.
    for i, (x, z, floor, family) in enumerate(HOMES):
        cx, front = x + 4.5, z + 6
        level['rooms'].append({'x': x, 'z': z, 'width': 9, 'depth': 6, 'height': 2.7,
            'floor_y': floor, 'material': 'home:hardwood_oak_01',
            'ceiling': {'kind': 'gable', 'ridge': 'x', 'ridge_rise': 1.6},
            'ceiling_material': 'home:ceiling_white_01',
            'comment': ('Raised lodge' if i == 0 else f'Cottage {i}') + ': shared shingle roof with temporary snow eaves.'})
        openings = [{'kind': 'door', 'offset': 3.93, 'width': 1.14, 'height': 2.15}]
        openings += [{'kind': 'window', 'offset': dx, 'width': 1.1, 'height': 1,
                      'sill': 1, 'glass': 'core:glass_window_clear_01', 'solid': True}
                     for dx in (1.1, 6.8)]
        level['walls'] += [
            {'x': x, 'z': front - .3, 'width': 9, 'depth': .3, 'y': floor,
             'material': 'outdoor:house_siding_01', 'faces': {'north': 'home:wall_paint_offwhite_01'},
             'openings': openings},
            {'x': x, 'z': z, 'width': 9, 'depth': .3, 'y': floor,
             'material': 'outdoor:house_siding_01', 'faces': {'south': 'home:wall_paint_offwhite_01'}},
            {'x': x, 'z': z + .28, 'width': .3, 'depth': 5.44, 'y': floor,
             'material': 'outdoor:house_siding_01', 'faces': {'east': 'home:wall_paint_offwhite_01'}},
            {'x': x + 8.7, 'z': z + .28, 'width': .3, 'depth': 5.44, 'y': floor,
             'material': 'outdoor:house_siding_01', 'faces': {'west': 'home:wall_paint_offwhite_01'}},
        ]
        prop(f'outdoor:house_{family}_wall_doorway', cx, front + .05, f'home_{i}_doorway', y=floor - .24)
        for dx in (0, 9):
            for dz in (0, 6):
                prop(f'outdoor:house_{family}_corner_trim', x + dx, z + dz, f'home_{i}_trim_{dx}_{dz}')
        level['doors'].append({'id': f'home_{i}_door', 'x': cx - .55, 'z': front - .15,
            'width': 1.1, 'height': 2.15, 'thickness': .045, 'open_direction': 'left',
            'swing_degrees': 90, 'open_speed_degrees': 100, 'initial_state': 'open',
            'kind': 'interior', 'frame_depth': .7, 'frame_center': .2,
            'components': [{'component': 'interactable', 'prompt': 'Lodge door' if i == 0 else 'Cottage door'}],
            'bindings': [{'on': 'interact', 'actions': [{'action': 'toggle'}]}]})
        # Two 1.4x kit bays span 9.52 m. Measured slopes meet at the ridge,
        # extend 0.64 m beyond the front/back walls, and clear the sealed ceiling.
        for bay, dx in enumerate((-2.38, 2.38)):
            for side, dz, yaw in (('front', 1.82, 0), ('back', -1.82, 180)):
                prop(f'outdoor:house_{family}_roof_slope', cx + dx, z + 3 + dz,
                     f'home_{i}_roof_{bay}_{side}', y=2.7, yaw=yaw, scale=1.4)
            prop(f'outdoor:house_{family}_roof_ridge', cx + dx, z + 3,
                 f'home_{i}_ridge_{bay}', y=4.996, scale=1.4)
        for side, dx, yaw in (('west', -4.65, 270), ('east', 4.65, 90)):
            base = .045217 if family == '01' else .060122
            prop(f'outdoor:house_{family}_gable', cx + dx, z + 3,
                 f'home_{i}_gable_{side}', y=floor + 2.7 - base * 2.4, yaw=yaw, scale=2.4)
        # Eaves are separate modular boxes, ready for later snow caps/icicles.
        for j, edge in enumerate((z, front)):
            box(f'home_{i}_eave_{j}', [x - .4, floor + 2.7, edge - .45],
                [x + 9.4, floor + 2.82, edge + .45], 'winter:snow_01')
        for dx in (-1.1, 1.1):
            lamp('outdoor:lamp_wall', cx + dx, front + .4, f'home_{i}_lamp_{dx}', y=floor + 1.79)
        level['ceiling_lights'].append({'id': f'home_{i}_light', 'fixture': 'home:ceiling_light_round',
            'x': cx + 1.3, 'z': z + 3.3, 'brightness': 1.1, 'range': 7,
            'color': [1, .83, .60], 'emission': 1, 'align': 'none'})
        prop('core:couch', x + 2, z + 1.4, f'home_{i}_couch', solid=True)
        prop('core:table', x + 2, z + 3.1, f'home_{i}_table', solid=True)
        prop('core:bed', x + 7, z + 2, f'home_{i}_bed', solid=True)
        prop('core:bookshelf', x + 7, z + 4.8, f'home_{i}_shelf', solid=True)
        if i:
            patch(cx - .85, front, 1.7, 4)

    # Partition ground at cottage bounds, with intermediate tile edges to
    # keep outdoor light grids compact. No snow floor hides under an interior.
    # Keep the lowered pond inside one room: a negative region crossing room
    # borders emits room-edge skirts, even when both rooms share floor_y.
    px, pz, pw, pd = POND_ROOM
    level['rooms'].append({'x': px, 'z': pz, 'width': pw, 'depth': pd,
        'height': 10, 'ceiling': {'kind': 'open'}, 'material': 'winter:snow_01',
        'comment': 'Pond shore: one room owns the entire recessed ice surface.'})
    level['geometry_intent'].append({'check': 'missing-wall', 'x': px, 'z': pz,
        'width': pw, 'depth': pd, 'note': 'Open pond and shoreline inside the visible rock boundary.'})
    zs = (-40, -30, -24, -18, -16, -10, -2, 0, 4, 10, 20)
    for za, zb in zip(zs, zs[1:]):
        active = [(x, z) for x, z, _, _ in HOMES if z < (za + zb) / 2 < z + 6]
        # Only split at a house's X bounds in the bands actually containing
        # that house. Global cuts would produce one-metre-wide probe-less rooms.
        pond_band = pz < (za + zb) / 2 < pz + pd
        xs = sorted({-24, 0, 24} | {edge for x, _ in active for edge in (x, x + 9)}
                    | ({px, px + pw} if pond_band else set()))
        xs = sorted(set(xs) | {(a + b) / 2 for a, b in zip(xs, xs[1:]) if b - a > 16})
        for xa, xb in zip(xs, xs[1:]):
            if (pond_band and px < (xa + xb) / 2 < px + pw) or any(x < (xa + xb) / 2 < x + 9 for x, _ in active):
                continue
            level['rooms'].append({'x': xa, 'z': za, 'width': xb - xa, 'depth': zb - za,
                'height': 10, 'ceiling': {'kind': 'open'}, 'material': 'winter:snow_01',
                'comment': 'Snow ground; one continuous walkable settlement.'})
            level['geometry_intent'].append({'check': 'missing-wall', 'x': xa, 'z': za,
                'width': xb - xa, 'depth': zb - za,
                'note': 'Deliberate outdoor snow floor, contained by visible collidable rock escarpments.'})
    for x, z, w, d in ((-26.2, -42.2, 2.2, 64.4), (24, -42.2, 2.2, 64.4),
                       (-24, -42.2, 48, 2.2), (-24, 20, 48, 2.2)):
        level['geometry_intent'].append({'check': 'room-leak', 'x': x, 'z': z, 'width': w, 'depth': d,
            'note': 'Outside authored floors, behind the visible solid rock boundary; native movement audits verify containment.'})

    # Central square, forest spine, cottage approaches and pond-side circuit.
    patch(-3, -5, 6, 10)
    patch(-1, -37, 2, 32)
    patch(-1, 5, 2, 12)
    patch(-11.5, -4.6, 11.5, 1.7)
    patch(0, -21.5, 12.5, 1.7)
    patch(11.65, -24, 1.7, 2.5)
    patch(-12.5, 12.3, 12.5, 1.7)
    patch(-13.35, 10, 1.7, 2.3)
    patch(3, -1.8, 15, 1.6)
    patch(17, -18, 1.6, 16.2)
    patch(0, -18, 18.6, 1.6)

    # Raised lodge deck: side stairs ascend +X; front ramp descends +Z.
    region(-15, -10, 7, 2.4, .6, 'home:hardwood_oak_01')
    level['stairs'].append({'x': -17.4, 'z': -9.6, 'width': 2.4, 'depth': 1.2,
        'offset_y': 0, 'rise': .6, 'steps': 3, 'material': 'winter:snow_packed_01',
        'riser_material': 'home:handrail_wood_01', 'side_material': 'home:handrail_wood_01'})
    level['ramps'].append({'x': -12.1, 'z': -7.6, 'width': 1.2, 'depth': 3,
        'offset_y': .6, 'rise': -.6, 'material': 'winter:snow_packed_01',
        'edge_material': 'winter:snow_01'})
    for x, length in ((-15, 2.85), (-10.85, 2.85)):
        level['guardrails'].append({'x': x, 'z': -7.65, 'y': .6, 'length': length,
            'height': 1.05, 'material': 'home:handrail_wood_01'})
    # Sheltered terrace has a supported roof and a 2.7 m clear ceiling.
    box('lodge_awning', [-15.2, 3.33, -10.05], [-7.8, 3.51, -7.45], 'winter:snow_01')
    for x in (-14.8, -8.2):
        prop('outdoor:house_02_porch_post', x, -7.85, f'porch_post_{x}', scale=1.187,
             solid=True, size=[.14, 2.3, .14])

    # An opaque, shallow, physical pond floor. No liquid/swim volume and no
    # friction changes: the later ice pass can attach behavior to this material.
    region(6, -16, 10, 12, -.16, 'winter:ice_01')
    for x, z, w, d in ((6, -16, 2, 2), (14, -16, 2, 2), (6, -6, 2, 2), (14, -6, 2, 2)):
        region(x, z, w, d, .18)
    # A pond railing leaves the west/south shore open for walking onto ice.
    level['guardrails'].append({'x': 16.8, 'z': -15, 'length': 10, 'rotation_degrees': 270,
        'height': 1.05, 'material': 'home:handrail_wood_01'})
    for i, (x, z) in enumerate(((-3.5, 2.5), (4, -2), (2.8, -21), (-12.5, 14.4))):
        lamp('outdoor:lamp_stand', x, z, f'path_lamp_{i}')
    for i, (x, z) in enumerate(((-3.8, -3), (13.8, -21.8))):
        lamp('outdoor:streetlight', x, z, f'square_lamp_{i}')
    for i, (x, z) in enumerate(((7, -18), (18.8, -10), (5, -5), (-6, -25), (-5, 6))):
        prop('outdoor:showcase_boulder', x, z, f'boulder_{i}', yaw=i * 47,
             scale=1 + (i % 3) * .18, solid=True)
    for i, (x, z) in enumerate(((-5.6, 1), (4.6, 3), (-3.5, -31))):
        prop('outdoor:showcase_stump_seat', x, z, f'seat_{i}', solid=True)

    # Visible high rock faces contain the map, without invisible blockers.
    for side, x, yaw in (('west', -24, 90), ('east', 24, 270)):
        for i in range(16):
            prop('outdoor:showcase_rock_face', x, -38 + i * 3.8, f'boundary_{side}_{i}',
                 yaw=yaw, solid=True, occludes=False)
    for side, z, yaw in (('north', -40, 0), ('south', 20, 180)):
        for i in range(13):
            prop('outdoor:showcase_rock_face', -23 + i * 3.8, z, f'boundary_{side}_{i}',
                 yaw=yaw, solid=True, occludes=False)

    # The canonical conifer stays untouched; the future snow variant will use
    # its exact 3.2 x 6.8 x 3.2 m box and source builder. Keep routes/canopies clear.
    rng = random.Random(20261006)
    for row, z in enumerate(range(-36, 18, 4)):
        for col, x in enumerate(range(-20, 22, 4)):
            px, pz = x + rng.uniform(-.6, .6), z + rng.uniform(-.6, .6)
            if abs(px) < 3 or (-6 < px < 6 and -7 < pz < 7): continue
            if any(hx - 2 < px < hx + 11 and hz - 2 < pz < hz + 10 for hx, hz, _, _ in HOMES): continue
            if -19 < px < -6 and -18 < pz < -3: continue
            if 3 < px < 20 and -20 < pz < 1: continue
            if -15 < px < 3 and 10 < pz < 16: continue
            if 0 < px < 15 and -24 < pz < -18: continue
            prop('outdoor:tree_03', px, pz, f'forest_{row}_{col}',
                 yaw=rng.uniform(0, 360), scale=rng.uniform(.9, 1.14),
                 solid=True, size=[.6, 6.8, .6], occludes=False)
    # Low banks keep elevation readable without placeholder snow-prop art.
    region(-21, -25, 5, 5, .28)
    level['ramps'].append({'x': -21, 'z': -20, 'width': 5, 'depth': 5.5,
        'offset_y': .28, 'rise': -.28, 'material': 'winter:snow_01', 'edge_material': 'winter:snow_01'})
    return level


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = serialise(build_level())
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != expected:
            print('Winter source is stale; run tools/levels/build_winter.py')
            return 1
        print('Winter source is deterministic and current')
    else:
        OUTPUT.write_text(expected)
        print(f'Authored {OUTPUT}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
